### ISSUE TITLE
Allow criteria for banner display and displayed data to differ

### ISSUE THREAD

**Issue by pbchase** [ctsit/data_driven_project_banner#17]
At the moment, this module allows for one query that determines _if_ the banner should be displayed and what data should be used for variable substitution in the text of the banner. Yet sometimes the criteria for these data differ. This is the case at UF in how we use the banner to draw attention to old, unpaid invoices. Any old unpaid invoice is a problem that warrants attention, but if we finally have someone's ear on the matter of paying their bill, we would be wise to tell them about all the unpaid invoices even the ones that are not past due. 

To that end, I think it would be wise to allow for separate queries: one for the display criteria; and one for the Content. This is in line with issue #16 which breaks with the idea of queries that return only one row. 

The query is in a field labeled "Prebuilt SQL". That might better be named "Criteria for display". As in the current design, one or more records would have to be returned by the "Criteria for display" query to satisfy the _Require a non-empty query result_ option.

The second query field could be named "Data to display in the body". It could be the same as the "Criteria for display", return more rows than "Criteria for display", or query a completely different table. I expect that the last option would still include the project_id in the query parameters, but I wouldn't say that was strictly required.

**Comment by ChemiKyle** [comment]
I think the "Require a non-empty query result" should be collapsed into the new "Criteria for display" option.  

![image](https://user-images.githubusercontent.com/20332546/120519912-2e5e1200-c3a1-11eb-9071-5d36da07ad6a.png)


"Always display" and "Require a non-empty query result" would be stand-ins for "Require a non-empty query result" being unchecked and checked, respectively.

___

Additionally, I'm wondering if we should allow custom queries for this field (and eventually "Data to display") by spawning a text box when "Custom query" is selected. Relegating this functionality to editing the `config.json` feels like a permutation of security through obscurity.

**Comment by pbchase** [comment]
> I think the "Require a non-empty query result" should be collapsed into the new "Criteria for display" option.
> ...
> "Always display" and "Require a non-empty query result" would be stand-ins for "Require a non-empty query result" being unchecked and checked, respectively.

Yes, that makes sense.

> Additionally, I'm wondering if we should allow custom queries for this field (and eventually "Data to display") by spawning a text box when "Custom query" is selected. Relegating this functionality to editing the `config.json` feels like a permutation of security through obscurity.

That's a fair criticism. Feel free to implement it or make an issue so we remember to do it later.

**Comment by ChemiKyle** [comment]
Addressed by #18
