### ISSUE TITLE
Allow for use of multiple banners

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/data_driven_project_banner#28]
Users are locked in to a single banner and a single query. Allowing for multiple banners would make this module infinitely more useful for both UF and any other users.

For the `config.json` this is as simple as wrapping all system level settings in a `"type": "sub_settings"` block with `"repeatable": "true"`.

`ExternalModule.php` will need to replace every call to `getSystemSetting` with logic that loops over equivalent results from `getSubsettings`. Potentially would want to

- overhaul `displayBanner` to accept the result of `getSubsettings` and perform `queryData` as part of that function.
- adapt `queryData` to return a list of responses.

`js/banner_inject.js` will need to index banners accordingly.

---

Keep in mind that user supplied queries are currently not implemented, perhaps bring this up at the next EM developer round table.

**Comment by pbchase** [comment]
@saipavan10-git, would you like to try your hand at this issue? I thought Kyle wrote it, but I have not located a PR or branch code that relates to this issue.

**Comment by saipavan10-git** [comment]
Sure I'll take a look into it.

**Comment by pbchase** [comment]
Addressed by PR #29
