### ISSUE TITLE
The text on the banner page is hard to read

### ISSUE THREAD

**Issue by pbchase** [ctsit/data_driven_project_banner#9]
The text on the banner page is hard to read.  The fine black text on the pinkish background is hard to read. Could you make the styling of the text customizable via CSS?

**Comment by ChemiKyle** [comment]
We could allow an additional field for custom CSS for the banner. There is also the option of a color picker field in settings we could implement as well.

**Comment by pbchase** [comment]
I like the idea of a CSS field to customize the banner. Provide a default hunk of CSS embedded in code, but allow it to be overridden via the configurable field.

**Comment by marlycormar** [comment]
@pbchase These are a couple options for the default banner design:

1. Red background & black border:

<img width="800" alt="Screen Shot 2019-11-14 at 11 10 01 AM" src="https://user-images.githubusercontent.com/8559654/68874706-a84f7d00-06cf-11ea-89ff-48e75193340f.png">

2. Red background & white border:

<img width="800" alt="Screen Shot 2019-11-14 at 11 09 43 AM" src="https://user-images.githubusercontent.com/8559654/68874799-c7e6a580-06cf-11ea-85d2-47659e35b69c.png">

3. Other color combinations?

**Comment by pbchase** [comment]
Red background with black border, please.

**Comment by marlycormar** [comment]
Sounds good.

**Comment by marlycormar** [comment]
@pbchase decided to go with the default design: white background & black border.
